apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: httpd-s2i
message: |-
  The following service(s) have been created in your project: ${NAME}.
  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/nginx-ex/blob/master/README.md.
metadata:
  annotations:
    description: An example Apache HTTP server that serves static content. For more information about using this template,
      including OpenShift considerations.
    iconClass: icon-apache
    openshift.io/display-name: Apache HTTP server
    openshift.io/documentation-url: https://github.com/sclorg/nginx-ex
    openshift.io/long-description: This HA template defines resources needed to develop
      a static application served by Apache HTTP serve including a build configuration and application deployment configuration.
    tags: quickstart,apache
  creationTimestamp: 2019-07-04T13:40:04Z
  name: httpd-s2i
  namespace: openshift
  resourceVersion: "222436"
  selfLink: /apis/template.openshift.io/v1/namespaces/openshift/templates/nginx-example-ha
  uid: 3ab02d03-9e61-11e9-bca1-02430d3d4786
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: master
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: httpd-s2i:2.4.39
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 2
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env: []
          image: ' '
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: nginx-example
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              cpu: ${CORE_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CORE_REQUEST}
              memory: ${MEMORY_REQUEST}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - apache-example
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: apache-example
- description: Minimum amount of core the container can use.
  displayName: Core Request
  name: CORE_REQUEST
  required: true
  value: "4"
- description: Maximum amount of memory the container can use.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 16Gi
- description: Maximum amount of core the container can use.
  displayName: Core Limit
  name: CORE_LIMIT
  required: true
  value: "4"
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 16Gi
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://gitlab.com/changdukkim/nginx-ex.git
- description: The exposed hostname that will route to the httpd service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: A secret string used to configure the Generic webhook.
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
