#!/bin/bash
LOCAL_SOURCE_DIR=/tmp/src
APACHE_ROOT=/usr/local/apache2
echo "---> Installing application source..."

# apps files
if [ -d $LOCAL_SOURCE_DIR/htdocs ]; then
  echo "Copying Application files from webapps of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/htdocs/* $APACHE_ROOT/htdocs/
fi

# configuration files
if [ -d $LOCAL_SOURCE_DIR/conf ]; then
  echo "Copying config files from conf of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/conf/* $APACHE_ROOT/conf/
fi


